version: '3'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp
    container_name: nodeapp
    ports:
      - '${APP_PORT:-80}:8080'
    env_file: .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: '${DB_PORT:-3306}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './src/www:/var/www/html'
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    image: 'mysql:5.7'
    ports:
      - '${DB_PORT:-3306}:3306'
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql:
    driver: local
